### ISSUE TITLE
PMS150G support?

### ISSUE THREAD

**Issue by lulersoft** [free-pdk/pdk-includes#11]
PMS150G support?

**Comment by serisman** [comment]
Looks like PMS150G/PMS15B is basically the same as PMS150C/PMS15A with the following changes:

FUSE options:
- PA5 (normal / open drain) instead of IO Drive (normal / low)
- Additional Super Fast Bootup option

Additional pull-low option for Port A.

I added the required files to the new-ics branch.  I do not have any PMS150G/PMS15B ICs to test with, so I can't confirm if these are the only required changes.

I would be interested if someone could read back locations 0x3F0 - 0x3FF from a blank/unprogrammed IC for me.  This would allow me to verify a few things such as the Factory Bandgap Trim Address, and the Default / Blank IC FUSE values.

**Comment by serisman** [comment]
Support for this will get merged up along with Pull Request: https://github.com/free-pdk/pdk-includes/pull/13

**Comment by serisman** [comment]
@lulersoft - not sure if you still need this or not, but were you able to pull down the new-ics branch and see if the new include files for PMS150G work for you?

**Comment by serisman** [comment]
I merged PR #13, so support for PMS150G should be there now.
